name=pqueue
version=0.1.0
author=Marco Gallotta
maintainer=Marco Gallotta
sentence=Persistent queue and outbox for embedded store-and-forward workloads.
paragraph=Persistent queue and outbox for embedded store-and-forward workloads.
category=Data Storage
url=https://github.com/marcogallotta/pqueue
architectures=*
includes=pqueue.h
