[platformio]
default_envs = esp32s3
test_dir = tests/arduino
src_dir = .

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_unflags =
  -std=gnu++11

build_flags =
    -std=gnu++17
    -Isrc

build_src_filter =
    +<src/>
    -<tools/>
    -<tests/>
    -<build/>

board_build.filesystem = littlefs

test_filter = test_pqueue_littlefs

[env:esp32s3-debug]
extends = env:esp32s3
build_flags =
    ${env:esp32s3.build_flags}
    -DLOG_LEVEL=APP_LOG_LEVEL_DEBUG

[env:esp32s3-slow]
extends = env:esp32s3
test_filter = test_pqueue_littlefs_slow

[env:esp32s3-soak]
extends = env:esp32s3
test_filter = test_pqueue_littlefs_soak

[env:esp32s3-spool-transfer]
extends = env:esp32s3
build_src_filter =
    +<src/>
    +<tools/esp32_spool_transfer/main.cpp>
    -<tests/>
    -<build/>
