[platformio]
default_envs = esp32s3-compaction
test_dir = tests/arduino

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    symlink://.

build_unflags =
  -std=gnu++11

build_flags =
    -std=gnu++17
    -Isrc

build_src_filter =
    +<src/>
    -<tools/>
    -<tests/>
    -<build/>

board_build.filesystem = littlefs

[env:esp32s3-compaction]
extends = env:esp32s3
test_filter = test_pqueue_compaction
build_flags = ${env:esp32s3.build_flags}
    -Itools

[env:esp32s3-littlefs]
extends = env:esp32s3
test_filter = test_pqueue_littlefs

[env:esp32s3-littlefs-slow]
extends = env:esp32s3
test_filter = test_pqueue_littlefs_slow

[env:esp32s3-littlefs-soak]
extends = env:esp32s3
test_filter = test_pqueue_littlefs_soak

[env:esp32s3-idle-sanity]
extends = env:esp32s3
test_filter = test_pqueue_idle_sanity

[env:esp32s3-benchmark]
extends = env:esp32s3
test_filter = test_pqueue_benchmark

