[platformio]
default_envs = esp32s3-doctor
src_dir = .

[env:esp32s3-doctor]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17

lib_deps =
    symlink://../..

board_build.filesystem = littlefs
